trigger: none

parameters:
- name: env
  values:
  - dev
  - qa   
  - prod
  
variables:
- template: template-variables.yml # Simple notation in template variable file.
  parameters:
    env: ${{ parameters.env }}

pool:
  vmImage: ubuntu-latest

steps:
- task: PowerShell@2
  displayName: Convert bicep YAML variables to JSON
  inputs:
    targetType: 'inline'
    script: |
      ls
      write-output  "${{ variables.bicepYAMLfile }}"
      write-output "${{ variables.bicepJSONfileNoEnv }}"
      copy-item  "${{ variables.bicepYAMLfile }}" "${{ variables.bicepJSONfileNoEnv }}"

- task: AzureCLI@2
  displayName: Create vnet RG
  inputs:
    azureSubscription: 'vsprof-dev'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az group create \
      --name ${{ variables.vnetResourceGroup }} \
      --location westeurope

- task: AzureCLI@2
  displayName: Deploy vnet/subnet with additional properties
  inputs:
    azureSubscription: 'vsprof-dev'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az deployment group create \
      --resource-group ${{ variables.vnetResourceGroup }} \
      --template-file main.bicep

